resource_types:
  - name: pool
    type: registry-image
    source: {repository: concourse/pool-resource, tag: 1.1.3}

  - name: azure-blobstore
    type: docker-image
    source:
      repository: pcfabr/azure-blobstore-resource

resources:
  - name: ci-src
    type: git
    source:
      uri: ((git-uri))
      branch: ((git-branch))
      private_key: ((ssh-private-key))
      paths:
        - .concourse

  - name: environment-azure
    type: pool
    source:
      uri: git@github.com:startreedata/startree-infra.git
      branch: environments
      pool: startree-platform/azure
      private_key: ((ssh-private-key))

  - name: thirdeye-helm-version
    type: semver
    source:
      driver: git
      uri: ((git-uri))
      branch: versions-((git-branch))
      file: startree-thirdeye-helm-chart-version

jobs:
- name: helm-deployment-validation
  serial_groups: ["integration-test"]
  plan:
    - put: environment-azure
      params:
        acquire: true
    - get: thirdeye-helm-version
      trigger: true
    - get: ci-src
    - task: install-thirdeye
      file: ci-src/.concourse/tasks/install-thirdeye/install-thirdeye.yml
      input_mapping:
        environment: environment-azure
        helm-version: thirdeye-helm-version
      params:
        VERSION_FILE: version/version
    - task: helm-test
      file: ci-src/.concourse/tasks/helm-test/helm-test-thirdeye.yml
      input_mapping:
        environment: environment-azure
      params:
        VERSION_FILE: version/version
    - task: cluster-cleanup
      file: ci-src/.concourse/tasks/cluster-cleanup/cleanup.yml
      input_mapping:
        environment: environment-azure
      params:
        VERSION_FILE: version/version
  ensure:
    put: environment-azure
    params:
      release: environment-azure